@isTest
public class AccountManagerTest {

    public static testmethod void testAccountManager()
    {
        id recordId = getTestAccountId();
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://surendrarestapi-developer-edition.na17.force.com/services/apexrest/Accounts/'+ recordId +'/contacts';
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        // Call the method to test
        Account  acc = AccountManager.getAccount();
        
        // Verify results
        System.assert(acc != null);
    }
    private static Id getTestAccountId(){
        Account acc = new Account(Name = 'TestAcc2');
        Insert acc;
         
        Contact con = new Contact(LastName = 'TestCont2', AccountId = acc.Id);
        Insert con;
        
        return acc.Id;
    }   
}